### ISSUE TITLE
Minor things

### ISSUE THREAD

**Issue by DominiqueMakowski** [wjschne/apaquarto#27]
Hey, just wanted to mention a few little potential improvements :)

1. In `jou` mode, increase space between authors and affiliations (and make affiliations smaller)

For comparison, this is papaja:

![image](https://github.com/wjschne/apaquarto/assets/8875533/19ea532a-039d-43fe-9e8e-23e6caabc431)

And here apaquarto

![image](https://github.com/wjschne/apaquarto/assets/8875533/ad7432b4-529e-42ee-b710-f221d68ac6a0)

---

2. Make the title bold (see above) looks arguably better

---

3. Clean-up the repo

A few images are lying at the base of the repo, which makes it look slightly messy (an orcid image, a badge etc.). I would recommend either removing them if possible (badges are typically directly copied from a shield.io URL, and for the Orcid I think there is another image under /_extensions/) or putting them in an "/img/" or "/assets/" folder. 

There is also an empty `.R` file that should be removed

---

4. I would add a screenshot of a rendered PDF / Word and put it in the README to give users an illustration of what the "final product" looks like. 

---

5. Restart line numbering (#25) at the beginning of body so that the line numbers don't change depending on whether it is masked or not

---

6. `jou` mode has this "ADD LEFTHEADER COMMAND" showing, not sure if that's expected

![image](https://github.com/wjschne/apaquarto/assets/8875533/82342b2e-c26d-4d00-8c98-c5a8bb6d7278)

---

7. Add the option to add the OrcID logo after the affiliation number in the author list; e.g.,

![image](https://github.com/wjschne/apaquarto/assets/8875533/421d2d29-e0cc-45c8-985a-e180e5f9cb59)

There seems to be a trend for that amongst most publishers.

---

8. Put the `fontsize` default value as a character `"12pt"` to avoid lintr syntax warning

![image](https://github.com/wjschne/apaquarto/assets/8875533/5bc055bc-5758-4bf6-beed-725b65a45a73)

---

9. Currently there are a lot of boolean variables to change the font type (`hrlv`, `tt`, etc.), and it makes it slightly confusing. I wonder if it would be helpful to streamline all that with a character argument; e.g., `fonttype: "typewriter"`

---

I'd be happy to take a stab at some of it but I have no idea where to edit the template...

**Comment by wjschne** [comment]
Thanks for the thorough suggestions. They have made this extension much better. 
 
> 1. In `jou` mode, increase space between authors and affiliations (and make affiliations smaller)

This is governed by the apa7 package. APA journals in practice have a variety of formats for the title page. It appears that the apa7 package's small space does in fact mimic the Journal of Educational Psychology as it claims to. See [this example](https://www.apa.org/pubs/journals/features/edu-edu0000564.pdf).

The papaja package follows the APA 6th Edition format. I am not sure if the extra space was required at the time.

If you think a spacing option should be included, let me know.
 
> For comparison, this is papaja:

> 2. Make the title bold (see above) looks arguably better

The problem was that the Times font was not loading and Computer Modern's regular face looks thin compared to that of Times. I think I have fixed the problem. If you think a bold option should be included, let me know.

> 3. Clean-up the repo
> 
> A few images are lying at the base of the repo, which makes it look slightly messy (an orcid image, a badge etc.). I would recommend either removing them if possible (badges are typically directly copied from a shield.io URL, and for the Orcid I think there is another image under /_extensions/) or putting them in an "/img/" or "/assets/" folder.

I have replaced the orcid image with a better one. I have removed the badge and use shield.io instead. 
I need the orcid image in the /_extensions/ folder to create HTML documents.


> There is also an empty `.R` file that should be removed

Removed. 

> 4. I would add a screenshot of a rendered PDF / Word and put it in the README to give users an illustration of what the "final product" looks like.

Great idea. Done.
> 
> 5. Restart line numbering ([Numbered lines #25](https://github.com/wjschne/apaquarto/issues/25)) at the beginning of body so that the line numbers don't change depending on whether it is masked or not

Done.

> 6. `jou` mode has this "ADD LEFTHEADER COMMAND" showing, not sure if that's expected

Done.

> 7. Add the option to add the OrcID logo after the affiliation number in the author list; e.g.,

This is done by the apa7 package. I am not sure how to override it.

> 
> 8. Put the `fontsize` default value as a character `"12pt"` to avoid lintr syntax warning

Done.

> 9. Currently there are a lot of boolean variables to change the font type (`hrlv`, `tt`, etc.), and it makes it slightly confusing. I wonder if it would be helpful to streamline all that with a character argument; e.g., `fonttype: "typewriter"`

I agree that it is confusing. The options come straight from the apa7 package.  I was not really sure why so many options exist, so I was reluctant to mess with it. If you have suggestions for a complete implementation, l am open to ideas.
