### ISSUE TITLE
Switch roles of `apa-note` and `fig-cap`

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#57]
Currently float (figure & table) captions go above the floats with a custom `apa-note` inserted below as caption. The [APA7 style](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/apa_tables_and_figures.html) calls the former "titles" and the latter "notes". 

Would it be possible standardize these to other common Quarto / Rmarkdown uses? Specifically they could be reversed, such that the typical captions (`tbl-cap`) would go below the floats, while the "note" could be renamed to (e.g.) `tbl-title` and `fig-title` and placed above the float. That is, map Quarto captions to APA7 "notes", and a custom variable to APA7 "titles".

IMHO this would make the template more in line with standard uses of those terms/variables and therefore more interoperable with other Quarto extensions and formats.

It would probably also allow not hard-coding the captions to go above the floats. I have tried to specify `fig-cap-location: bottom` in a few different places but it doesn't seem to have any effect.

Edit: I should say if this sounds desirable feel free to assign the issue to me and I am happy to try to submit a PR. 🚀

**Comment by wjschne** [comment]
To get a float number in Quarto, the caption must be specified. In APA style, every float must have a title, but notes are optional. Therefore, I made the title correspond with the caption because both are required. If the roles of title and caption were altered, we would have to figure out what to do when someone wants a title but not a note.

I think that we can explore making variants of the caption placement. Right now, there are no options.

**Comment by mvuorre** [comment]
Understood, thanks!

I will probably work on a fork of this that makes it compatible with other formats regarding the caption (remove the note and move captions below floats.)
